Add a benchmark for Buf.send()
netty/netty-incubator-buffer-api pull request #13
Opened 2020-12-04 15:27 UTC by chrisvest

Motivation:
This will likely be a somewhat common operation, as buffers move between eventloop and worker threads, so it's important to have an understanding of how it performs.

Modification:
Add a benchmark that specifically targets the send() operation on buffers.

Result:
We got benchmark numbers that clearly show the cost of confinement transfer

2020-12-04 16:20 UTC, chrisvest commented
The `cleanerClose/heavy` case became slower, I think, because now it doesn't have much advantage compared to explicitly closed. Basically, those two cases aligned, while previously the cleaner case could upgrade the segment to a shared one and then forego its costs of closing.

2020-12-04 16:55 UTC, chrisvest commented
I was worried that the transfer thread was perhaps not going to be a scalable solution on a loaded system, but it turns out that the performance benefit is even more pronounced then.

When running the benchmark with `-t 8`:

Before

```
Benchmark                    Mode  Cnt    Score   Error  Units
SendBenchmark.sendNonPooled  avgt   50  419,389 ± 6,732  us/op
SendBenchmark.sendPooled     avgt   50   17,409 ± 0,303  us/op
```

After

```
Benchmark                    Mode  Cnt   Score   Error  Units
SendBenchmark.sendNonPooled  avgt   50  42,229 ± 1,884  us/op
SendBenchmark.sendPooled     avgt   50  18,153 ± 0,347  us/op
```

2020-12-04 17:00 UTC, normanmaurer requested changes

2020-12-04 17:00 UTC, normanmaurer commented on src/main/java/io/netty/buffer/api/memseg/MemSegBuf.java
> +            throw new RuntimeException(e);
should we just call `Thread.currentThread().interrupt()` and return ?

2020-12-04 17:00 UTC, normanmaurer commented on src/main/java/io/netty/buffer/api/memseg/MemSegBuf.java
> +        TRANSFER_THREAD.setDaemon(true);
I can just tell you from experience that people sometimes are very sensitive to threads that are created in the background and basically never exists. ..

2020-12-04 17:00 UTC, normanmaurer commented on src/main/java/io/netty/buffer/api/memseg/MemSegBuf.java
> +        TRANSFER_THREAD.start();
You should ensure you reset the class loader to not leak at the end 

https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/ObjectCleaner.java#L111

2020-12-04 17:00 UTC, normanmaurer commented on src/main/java/io/netty/buffer/api/memseg/MemSegBuf.java
> +        } else {
nit: you can remove the `else` as you return before.

2020-12-04 17:00 UTC, normanmaurer commented on src/test/java/io/netty/buffer/api/benchmarks/SendBenchmark.java
> +    private static final Function<Send<Buf>, Send<Buf>> bounce = send -> {
nit: consider using upper-case for the names to be inlines with the JLS recommendation of static fields

2020-12-04 17:00 UTC, normanmaurer commented on src/test/java/io/netty/buffer/api/benchmarks/SendBenchmark.java
> + * Copyright 2019 The Netty Project
2020

2020-12-04 17:26 UTC, chrisvest commented on src/main/java/io/netty/buffer/api/memseg/MemSegBuf.java
> +        TRANSFER_THREAD.setDaemon(true);
Do you have an alternative in mind?

2020-12-04 17:43 UTC, chrisvest commented
@normanmaurer I'll split out the benchmark in a separate PR, since that'll be less controversial.

2020-12-18 13:58 UTC, chrisvest commented
Closing this because it becomes a non-issue (no more thread-ownership transitions) when we remove thread-confinement in #21

2020-12-18 13:58 UTC, closed without merging