Move to custom exception types
netty/netty-incubator-buffer-api pull request #73
Opened 2021-05-28 13:16 UTC by kashike

Opening this to get some initial feedback before continuing.

Rather than using a single type (`IllegalStateException`) when notifying consumers about exceptions, use custom ones - this makes catching and handling exceptions easier.

2021-05-28 13:53 UTC, kashike commented
@chrisvest When you have a minute, please take a look and see what you think before I continue. Started this before the comments in #70.

2021-05-28 14:00 UTC, chrisvest commented
@kashike I like the idea. I think the exceptions should be defined in each their own class, though.

2021-05-28 15:21 UTC, chrisvest requested changes

2021-05-28 15:21 UTC, chrisvest commented on buffer-api/src/main/java/io/netty/buffer/api/internal/ResourceSupport.java
> +            throw attachTrace(new BufferClosedException("This resource is closed: " + this + '.'));
`ResourceSupport` should not be buffer specific. We can delegate the exception creation to a protected abstract method that subclasses override. Then we can also make the exception message be "This _buffer_ is closed…"

2021-05-28 15:21 UTC, chrisvest commented on buffer-api/src/main/java/io/netty/buffer/api/Buffer.java
> +     * @throws IllegalStateException if this buffer is not in a bad state.
Remove "not" – makes the rebase easier when #72 and this eventually conflicts.

2021-05-28 15:21 UTC, chrisvest commented on buffer-api/src/main/java/io/netty/buffer/api/Buffer.java
> +     * @throws IllegalStateException if this buffer is not in a bad state.
Remove "not" – makes the rebase easier when #72 and this eventually conflicts.

2021-05-28 15:21 UTC, chrisvest commented on buffer-api/src/main/java/io/netty/buffer/api/Buffer.java
> +     * @throws IllegalStateException if this buffer is not in a bad state.
Remove "not" – makes the rebase easier when #72 and this eventually conflicts.

2021-05-28 15:21 UTC, chrisvest commented
Also, I've no idea why test report uploading keeps failing on your PRs but works on mine 🤷

2021-05-28 15:24 UTC, normanmaurer commented
@chrisvest I wonder if the uploading this is some sort of a permission problem. I had the same problem in netty at some point and so switched to the extra workflow for it:

https://github.com/netty/netty/blob/4.1/.github/workflows/ci-pr-reports.yml

2021-05-28 16:37 UTC, chrisvest commented
@kashike I merged a separate workflow for uploading test results, so if you rebase _maybe_ that part will work now.

2021-05-28 16:59 UTC, normanmaurer commented on buffer-api/src/main/java/io/netty/buffer/api/BufferClosedException.java
> +public class BufferClosedException extends IllegalStateException {
I think I would mark all our exceptions as final for now.

2021-05-28 17:00 UTC, normanmaurer requested changes

2021-05-28 17:00 UTC, normanmaurer commented on buffer-api/src/main/java/io/netty/buffer/api/BufferReadOnlyException.java
> +public class BufferReadOnlyException extends IllegalStateException {
Why we don't just use what the JDK provides here ? 

https://docs.oracle.com/javase/7/docs/api/java/nio/ReadOnlyBufferException.html

At least I would extend what the JDK provides as `UnsupportedOperationException` sounds also more correct.

2021-05-28 18:44 UTC, kashike commented on buffer-api/src/main/java/io/netty/buffer/api/BufferReadOnlyException.java
> +public class BufferReadOnlyException extends IllegalStateException {
The JDK class does not allow specifying a message.

2021-05-28 18:44 UTC, kashike commented on buffer-api/src/main/java/io/netty/buffer/api/BufferReadOnlyException.java
> +public class BufferReadOnlyException extends IllegalStateException {
I have changed the parent of ours to `UnsupportedOperationException`.

2021-05-28 18:51 UTC, kashike commented
I've addressed the comments left earlier.

2021-05-28 19:37 UTC, kashike commented
I have had to do some... ugly things to the tests. Due to the exceptions now having different parents, it becomes a mess. Perhaps we should introduce a root exception type (`BufferException extends RuntimeException`) for our exceptions to extend?

2021-05-31 09:23 UTC, chrisvest requested changes
Thanks for doing this work. I had a bunch of comments. Please take a look.

2021-05-31 09:23 UTC, chrisvest commented on buffer-api/src/main/java/io/netty/buffer/api/internal/Statics.java
> +        return new BufferReadOnlyException("This buffer is read-only.");
Why do these two take `Buffer` as arguments now?

2021-05-31 09:23 UTC, chrisvest commented on buffer-tests/src/test/java/io/netty/buffer/api/tests/BufferComponentIterationTest.java
> +            assertThrows(UnsupportedOperationException.class, () -> buf.forEachWritable(0, (index, component) -> true));
Why is this not `BufferClosedException`?

2021-05-31 09:23 UTC, chrisvest commented on buffer-tests/src/test/java/io/netty/buffer/api/tests/BufferCompositionTest.java
> +            );
Stray line break

2021-05-31 09:23 UTC, chrisvest commented on buffer-api/src/main/java/io/netty/buffer/api/internal/ResourceSupport.java
> +import io.netty.buffer.api.BufferClosedException;
This import can be removed now.

2021-05-31 09:23 UTC, chrisvest commented on buffer-api/src/main/java/io/netty/buffer/api/adaptor/ByteBufAdaptor.java
> +        } catch (IllegalStateException | UnsupportedOperationException e) {
I think all of these should just catch `BufferClosedException` and let any `BufferReadOnlyException` bubble through. Buffers being read-only is not a reference count issue. The illegal state probably is, though, so let's keep that.

2021-05-31 09:23 UTC, chrisvest commented on buffer-tests/src/test/java/io/netty/buffer/api/tests/BufferReadOnlyTest.java
> +            assertTrue(c1e instanceof IllegalStateException || c1e instanceof UnsupportedOperationException);
We should assert that this specifically throws `BufferReadOnlyException`.

2021-05-31 09:23 UTC, chrisvest commented on buffer-tests/src/test/java/io/netty/buffer/api/tests/BufferReadOnlyTest.java
> +                assertTrue(c1e instanceof IllegalStateException || c1e instanceof UnsupportedOperationException);
These should also assert on `BufferReadOnlyException`.

2021-05-31 09:23 UTC, chrisvest commented on buffer-tests/src/test/java/io/netty/buffer/api/tests/BufferReadOnlyTest.java
> +                assertTrue(c2e instanceof IllegalStateException || c2e instanceof UnsupportedOperationException);
📌

2021-05-31 09:23 UTC, chrisvest commented on buffer-tests/src/test/java/io/netty/buffer/api/tests/BufferReadOnlyTest.java
> +                assertTrue(c3e instanceof IllegalStateException || c3e instanceof UnsupportedOperationException);
📌

2021-05-31 09:23 UTC, chrisvest commented on buffer-tests/src/test/java/io/netty/buffer/api/tests/BufferReferenceCountingTest.java
> +            assertThrows(UnsupportedOperationException.class, () -> acquire((ResourceSupport<?, ?>) buf));
This should assert on `BufferClosedException`.

2021-05-31 09:23 UTC, chrisvest commented on buffer-tests/src/test/java/io/netty/buffer/api/tests/BufferTestSupport.java
> +        verifyWriteInaccessible(buf, BufferClosedException.class, IllegalStateException.class);
This is shining light on a bug in `ensureWritable`. It should throw `BufferClosedException` in these cases, and we can then collapse this to one parameter.

2021-05-31 09:23 UTC, chrisvest commented on buffer-tests/src/test/java/io/netty/buffer/api/tests/BufferReadOnlyTest.java
> +            final RuntimeException c1e = assertThrows(RuntimeException.class, () -> buf.compact());
This needs to assert on `BufferReadOnlyException` and `NioBuffer` needs to comply.

2021-05-31 09:23 UTC, chrisvest commented on buffer-tests/src/test/java/io/netty/buffer/api/tests/BufferReadOnlyTest.java
> +                assertTrue(c1e instanceof IllegalStateException || c1e instanceof UnsupportedOperationException);
Same here. `NioBuffer` is wrong for diverging.

2021-05-31 09:23 UTC, chrisvest commented on buffer-tests/src/test/java/io/netty/buffer/api/tests/BufferReadOnlyTest.java
> +                assertTrue(c2e instanceof IllegalStateException || c2e instanceof UnsupportedOperationException);
📌

2021-05-31 09:23 UTC, chrisvest commented on buffer-tests/src/test/java/io/netty/buffer/api/tests/BufferReadOnlyTest.java
> +                assertTrue(c3e instanceof IllegalStateException || c3e instanceof UnsupportedOperationException);
📌

2021-05-31 09:23 UTC, chrisvest commented on buffer-tests/src/test/java/io/netty/buffer/api/tests/BufferRefTest.java
> +            assertTrue(w1e instanceof IllegalStateException || w1e instanceof UnsupportedOperationException);
This should assert on `BufferClosedException`.

2021-05-31 09:23 UTC, chrisvest commented on buffer-tests/src/test/java/io/netty/buffer/api/tests/BufferRefTest.java
> +            assertThrows(UnsupportedOperationException.class, () -> ref.contents().writeInt(32));
This should be `BufferClosedException`.

2021-05-31 09:23 UTC, chrisvest commented on buffer-tests/src/test/java/io/netty/buffer/api/tests/BufferRefTest.java
> +            assertTrue(w1e instanceof IllegalStateException || w1e instanceof UnsupportedOperationException);
These two should assert on `BufferClosedException`.

2021-05-31 09:23 UTC, chrisvest commented on buffer-tests/src/test/java/io/netty/buffer/api/tests/BufferRefTest.java
> +            assertTrue(w2e instanceof IllegalStateException || w2e instanceof UnsupportedOperationException);
📌

2021-05-31 09:23 UTC, chrisvest commented on buffer-tests/src/test/java/io/netty/buffer/api/tests/BufferRefTest.java
> +            assertTrue(w2e instanceof IllegalStateException || w2e instanceof UnsupportedOperationException);
Same for these two. Looks like this test got duplicated somehow (the one above this one is the duplicate, which can be removed).

2021-05-31 09:23 UTC, chrisvest commented on buffer-tests/src/test/java/io/netty/buffer/api/tests/BufferRefTest.java
> +            assertTrue(r1e instanceof IllegalStateException || r1e instanceof UnsupportedOperationException);
This should assert on `BufferClosedException`.

2021-05-31 09:23 UTC, chrisvest commented on buffer-tests/src/test/java/io/netty/buffer/api/tests/BufferTestSupport.java
> +            assertThrows(UnsupportedOperationException.class, () -> buf.copyInto(0, ByteBuffer.allocate(1), 0, 1));
These `UnsupportedOperationException` can be `BufferClosedException`.

2021-05-31 09:23 UTC, chrisvest commented on buffer-tests/src/test/java/io/netty/buffer/api/tests/BufferTestSupport.java
> +        assertThrows(UnsupportedOperationException.class, () -> buf.openReverseCursor(0, 0));
All of these should be `BufferClosedException` as well.

The `split` and `send` methods will need some `isAccessible` checks before their `isOwned` checks.

2021-05-31 09:23 UTC, chrisvest commented on buffer-tests/src/test/java/io/netty/buffer/api/tests/BufferTestSupport.java
> +        assertThrows(UnsupportedOperationException.class, () -> buf.getDouble(0));
All of these also need to assert on `BufferClosedException` – pure read methods cannot throw `BufferReadOnlyException`.

2021-05-31 18:21 UTC, kashike commented on buffer-tests/src/test/java/io/netty/buffer/api/tests/BufferReadOnlyTest.java
> +            assertTrue(c1e instanceof IllegalStateException || c1e instanceof UnsupportedOperationException);
They don't just throw this, which is why it was changed. 
> org.opentest4j.AssertionFailedError: Unexpected exception type thrown ==> expected: <io.netty.util.IllegalReferenceCountException> but was: <io.netty.buffer.api.BufferClosedException>

2021-05-31 18:28 UTC, kashike commented on buffer-tests/src/test/java/io/netty/buffer/api/tests/BufferReadOnlyTest.java
> +            final RuntimeException c1e = assertThrows(RuntimeException.class, () -> buf.compact());
What would you prefer, moving the read-only check above the owned check?

2021-05-31 18:51 UTC, kashike commented
I've pushed some of the requested changes, with around 200 tests failing locally.

2021-06-01 10:08 UTC, chrisvest approved these changes
I fixed the remaining issues

2021-06-01 10:33 UTC, kashike commented
Cheers @chrisvest - I was not sure what you had in mind.

2021-06-01 10:33 UTC, merged